CREATE TABLE "TB_Usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "TB_Paciente" (
  "id_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int
);

CREATE TABLE "TB_Medico" (
  "id_medico" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int,
  "crm" varchar
);

CREATE TABLE "RL_DEPENDENTE" (
  "id_responsavel" int,
  "id_dependente" int
);

CREATE TABLE "RL_MEDICO_DEPENDENTE" (
  "id_medico" int,
  "id_paciente" int
);

CREATE TABLE "TB_Exame" (
  "idExame" int PRIMARY KEY,
  "name" varchar,
  "url" varchar,
  "id_Paciente" int
);

CREATE TABLE "TB_Dados_Saude" (
  "idDadosSaude" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "RL_Dados_Saude_Exame" (
  "id_rl_dados_saude_exame" int PRIMARY KEY,
  "id_Exame" int,
  "id_Dados_Saude" int
);

ALTER TABLE "TB_Paciente" ADD FOREIGN KEY ("id_usuario") REFERENCES "TB_Usuario" ("id");

ALTER TABLE "TB_Medico" ADD FOREIGN KEY ("id_usuario") REFERENCES "TB_Usuario" ("id");

ALTER TABLE "RL_DEPENDENTE" ADD FOREIGN KEY ("id_responsavel") REFERENCES "TB_Paciente" ("id_paciente");

ALTER TABLE "RL_DEPENDENTE" ADD FOREIGN KEY ("id_dependente") REFERENCES "TB_Paciente" ("id_paciente");

ALTER TABLE "RL_MEDICO_DEPENDENTE" ADD FOREIGN KEY ("id_medico") REFERENCES "TB_Medico" ("id_medico");

ALTER TABLE "RL_MEDICO_DEPENDENTE" ADD FOREIGN KEY ("id_paciente") REFERENCES "TB_Paciente" ("id_paciente");

ALTER TABLE "TB_Exame" ADD FOREIGN KEY ("id_Paciente") REFERENCES "TB_Paciente" ("id_paciente");

ALTER TABLE "RL_Dados_Saude_Exame" ADD FOREIGN KEY ("id_Exame") REFERENCES "TB_Exame" ("idExame");

ALTER TABLE "RL_Dados_Saude_Exame" ADD FOREIGN KEY ("id_Dados_Saude") REFERENCES "TB_Dados_Saude" ("idDadosSaude");