CREATE TABLE "TB_Usuario" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "nome" varchar(500)
);

CREATE TABLE "TB_Paciente" (
                               "id_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "id_usuario" int,
                               "id_status_formulario" int,
                               "email" varchar(500),
                               "senha" varchar(500),
                               "nome" varchar(500),
                               "dt_nascimento" date,
                               "criado_em" date,
                               "formulario" varchar(500)
);

CREATE TABLE "TB_Medico" (
                             "id_medico" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "id_usuario" int,
                             "crm" varchar(500),
                             "especialidade" varchar(500),
                             "email" varchar(500),
                             "senha" varchar(500),
                             "nome" varchar(500),
                             "dt_nascimento" date,
                             "criado_em" date
);

CREATE TABLE "RL_DEPENDENTE" (
                                 "id_responsavel" int,
                                 "id_dependente" int
);

CREATE TABLE "TB_Atende" (
                             "id_medico" int,
                             "id_paciente" int
);

CREATE TABLE "TB_Exame" (
                            "idExame" int PRIMARY KEY,
                            "name" varchar(500),
                            "arquivo" varchar(500),
                            "date_adicao" date,
                            "id_Paciente" int
);

CREATE TABLE "TB_Dados_Saude" (
                                  "idDadosSaude" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "nome" varchar(500)
);

CREATE TABLE "RL_Dados_Saude_Exame" (
                                        "id_rl_dados_saude_exame" int PRIMARY KEY,
                                        "id_Exame" int,
                                        "id_Dados_Saude" int
);

CREATE TABLE "TP_Status_Formulario" (
                                        "id_status_formulario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        "status_formulario" varchar(500)
);

ALTER TABLE "TB_Paciente" ADD FOREIGN KEY ("id_usuario") REFERENCES "TB_Usuario" ("id");

ALTER TABLE "TB_Medico" ADD FOREIGN KEY ("id_usuario") REFERENCES "TB_Usuario" ("id");

ALTER TABLE "RL_DEPENDENTE" ADD FOREIGN KEY ("id_responsavel") REFERENCES "TB_Paciente" ("id_paciente");

ALTER TABLE "RL_DEPENDENTE" ADD FOREIGN KEY ("id_dependente") REFERENCES "TB_Paciente" ("id_paciente");

ALTER TABLE "TB_Atende" ADD FOREIGN KEY ("id_medico") REFERENCES "TB_Medico" ("id_medico");

ALTER TABLE "TB_Atende" ADD FOREIGN KEY ("id_paciente") REFERENCES "TB_Paciente" ("id_paciente");

ALTER TABLE "TB_Exame" ADD FOREIGN KEY ("id_Paciente") REFERENCES "TB_Paciente" ("id_paciente");

ALTER TABLE "RL_Dados_Saude_Exame" ADD FOREIGN KEY ("id_Exame") REFERENCES "TB_Exame" ("idExame");

ALTER TABLE "RL_Dados_Saude_Exame" ADD FOREIGN KEY ("id_Dados_Saude") REFERENCES "TB_Dados_Saude" ("idDadosSaude");

ALTER TABLE "TB_Paciente" ADD FOREIGN KEY ("id_status_formulario") REFERENCES "TP_Status_Formulario" ("id_status_formulario");
