version: '3.8'

services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
