name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Deploy to PostgreSQL
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Execute init.sql
        env:
          PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          psql -h ${{ secrets.DATABASE_HOST }} -U ${{ secrets.DATABASE_USER }} -d ${{ secrets.DATABASE_NAME }} -f init.sql

      - name: Execute init_data.sql
        env:
          PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          psql -h ${{ secrets.DATABASE_HOST }} -U ${{ secrets.DATABASE_USER }} -d ${{ secrets.DATABASE_NAME }} -f init_data.sql
